### ISSUE TITLE
iuclid 6 6.14.3 compatibility

### ISSUE THREAD

**Issue by Javier-CP** [Mark-R-R/automatic_report_generation_scripts#2]
Hello,
the report generation script doesn't seem to work when using it to generate reports with the iuclid 6 release 6.14.3.
I'm getting error 500 all the time, for example this one:
[07_32_18-28-April-2022_PAR-49c31af8-73fb-42e3-af38-e9b42b3db83b.pdf](https://github.com/echa-ecm/automatic_report_generation_scripts/files/8579867/07_32_18-28-April-2022_PAR-49c31af8-73fb-42e3-af38-e9b42b3db83b.pdf)

The server log is the following:

[log.txt](https://github.com/echa-ecm/automatic_report_generation_scripts/files/8579869/log.txt)

Did you notice a similar issue?
Best regards

**Comment by echa-ecm** [comment]
Hi Javier,

I get the same error. I will look into this and get back to you.

Thanks,
Mark

**Comment by echa-ecm** [comment]
Hi @Javier-CP - the new script is now available. Note that this new script only works with v6.14.3 and onwards.
